services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - paymybuddy-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=paymybuddy
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - paymybuddy-network

networks:
  paymybuddy-network:
    driver: bridge

volumes:
  mysql-data: