services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8080:8080"
    depends_on:
      - db-test
    environment:
      - SPRING_DATASOURCE_URL=${DB_TEST_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_TEST_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_TEST_PASSWORD}
      - SPRING_PROFILES_ACTIVE=test
    networks:
      - paymybuddy-test-network
    volumes:
      - ./target:/app/target
    command: mvn verify

  db-test:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_TEST_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_TEST_PASSWORD}
    networks:
      - paymybuddy-test-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  paymybuddy-test-network:
    driver: bridge