# Dockerfile.test
# Image optimisée pour l'exécution des tests dans le pipeline CI/CD

FROM eclipse-temurin:21-jdk

# Installation de Maven
RUN apt-get update && \
    apt-get install -y maven git curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Configuration de Maven
RUN mkdir -p /root/.m2
COPY .mvn /root/.m2

WORKDIR /app

# Copie du fichier POM pour télécharger les dépendances
COPY pom.xml .
COPY src ./src