services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8080:8080"
    depends_on:
      - db-test
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-test:3306/paymybuddy_test?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - DB_HOST=db-test
      - SPRING_PROFILES_ACTIVE=test
    networks:
      - paymybuddy-test-network
    volumes:
      - ./target:/app/target
    command: mvn verify

  db-test:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=paymybuddy_test
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - paymybuddy-test-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  paymybuddy-test-network:
    driver: bridge