# Dockerfile pour tests

# Dockerfile.test
# Image optimisée pour l'exécution des tests dans le pipeline CI/CD

FROM eclipse-temurin:21-jdk

# Installation des outils nécessaires
RUN apt-get update && \
    apt-get install -y maven git curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Configuration de Maven
RUN mkdir -p /root/.m2
COPY .mvn /root/.m2

WORKDIR /app

# Copie du fichier POM pour précharger les dépendances
COPY pom.xml .
# Préchargement des dépendances Maven pour accélérer les builds futurs
RUN mvn dependency:go-offline -B

# Copie du code source
COPY src ./src