spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
