name: PayMyBuddy CI/CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: paymybuddy_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Unit Tests
        run: mvn test

      - name: Run Integration Tests
        run: mvn failsafe:integration-test

      - name: Generate JaCoCo Coverage Report
        run: mvn jacoco:report

      - name: Copy JaCoCo Report to docs folder
        run: |
          mkdir -p docs/jacoco
          cp -r target/site/jacoco/* docs/jacoco/

      - name: Commit and push updated docs to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add docs/
          git commit -m "Update JaCoCo report"
          git push origin HEAD:gh-pages
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
